---
title: "About us"
output:
  html_document:
    toc: true
    toc_float: true
    theme: cerulean
---

__Here is our information__

All members of our groups are from [Columbia University Irving Medical Center (CUIMC)](https://www.cuimc.columbia.edu/). 
You access their resume for detailed information. 

## Yuchen Hua ##  
__Yuchen Hua__ currently is a first year students in CUIMC, [Mailman School of Public Health](https://www.cuimc.columbia.edu/education/mailman-school-public-health), department of [Biostatistics](https://www.publichealth.columbia.edu/academics/departments/biostatistics) in CUMC, track [Public Health Data Science (PHDS)](https://www.publichealth.columbia.edu/academics/degrees/master-science/public-health-data-science). 

Yuchen used to be a B.S in Biochemistry from [Brandeis University](https://www.brandeis.edu/). During his undergraduate period, he has researched on Computational Study of COVID-19 Antibodies and Structural Implications on Future Antibody Development, supervised under Prof. [Buyong Ma](https://pharm.sjtu.edu.cn/en/szdw/2747.html). 
Meanwhile, Yuchen used to be a research assistant to organize and clean data during his summer internship in [Soochow University Affiliated Dushu Lake Hospital](https://www.sdhmdp.com/).

[Resume](CV Yuchen Hua .pdf)

## Hongpu Min ##
__Hongpu Min__ currently is a student in CUIMC, [Mailman School of Public Health](https://www.cuimc.columbia.edu/education/mailman-school-public-health), department of [Biostatistics](https://www.publichealth.columbia.edu/academics/departments/biostatistics) in CUMC, track [Public Health Data Science (PHDS)](https://www.publichealth.columbia.edu/academics/degrees/master-science/public-health-data-science). 

Hongpu used to be a B.S. in Applied Mathesmatics and B.A. in Economics from the [University of Carlifonia Santa Barbara](https://www.ucsb.edu/). During this undergraduate period, Hongpu has been remote researcher assistant in Laboratory of Structural Cell Biology at Emory University and remote researcher in [Mercer University](https://www.mercer.edu/), to process statistical study of Relationship Between Dental Materials Supply Chain and Benefited Group. 

[Resume](Hongpu Min Resume.pdf)



## Jennifer Mizhquiri ##     
__Jennifer Mizhquiri__ is currrently a student in CUIMC, [Mailman School of Public Health](https://www.cuimc.columbia.edu/education/mailman-school-public-health), department of [Health Policy and Management](https://www.publichealth.columbia.edu/academics/departments/health-policy-and-management), pursuing Master in Public health. She is a project manager at [Center for Behavioral Cardiovascular Health (CBCH)](https://www.columbiacardiology.org/research/research-centers-and-programs/center-behavioral-cardiovascular-health) working in an interdisciplinary lab focused on implementation science methodologies.

Jennifer did her B.A. in Literatures in English at [Cornell University](https://www.cornell.edu/). During her undergraduate period, she was a student treasurer to reconciled student expenditures Cornell student assembly reimbursement policies during academic terms and monitored budget goals and participated in a student martial arts group.

[Resume](20221021_Resume_MizhquiriBarbecho_Jennifer.pdf)

## Michael Denham ##     
__Michael Denham__ currently is a student in CUIMC, [Vagelos College of Physicians and Surgeions](https://www.vagelos.columbia.edu/). He is a MD/MS in Biomedical Sciences Candidate. From 2020, he has been a Co-Investigator in Columbia University, supervised under [Dr. Anil Lalwani](https://www.entcolumbia.org/profile/aklalwani) at Columbia Department of Otolaryngology-Head & Neck Surgery.

From 2018 to July of 2019, Michael studied in [Churchill College, University of Cambridge](https://www.chu.cam.ac.uk/), [Department of History and Philosophy of Science](https://www.hps.cam.ac.uk/). He achieved his MPhil in Health, Medicine, & Soceity there and graduated with Distinction. From 2018 to 2020, he was a co-investigator on a retrospective study examining the impact of surgical positioning on patient outcomes in total hip arthoplasty, supervised under [Dr. Jeffrey Geller](https://doctors.columbia.edu/us/ny/tarrytown/jeffrey-a-geller-md-155-white-plains-road) at the Columbia Department of Orthopedics. Meanwhile, he was also a tutor for math, economics, and admissions tests. 

In May of 2018, Michael graduated from [Louisiana State University Honors College](http://www.honors.lsu.edu/) as a Summa cum laude, Phi Beta Kappa, B.S. in Chemical Engineering and B.A. in Economics. From 2014 to 2018, he was a research assistant in [Batzer Laboratory of Comparative Genomics](https://biosci-batzerlab.biology.lsu.edu/).

In August of 2016, Michael achieved __CORe: Credential of Readiness, Pass with High Honors__ from HBX at Harvard Business School. 

[Resume](Michael Denham_CV_11.22.2022.pdf)

## Contact Infomation ##
__Yuchen Hua__

Email: yh3555@cumc.columbia.edu

Mobile: (781)296-5628


__Hongpu Min__


__Jennifer Miahquiri Barbecho__

Email: jsm2182@cumc.columbia.edu

Mobile: (212) 342-4141


__Michael W.Denham__

Email: michael.denham@columbia.edu

Mobile: (504) 201-4316






