---
title: "Explore our Data"
subtitle: "NHANES (2017) - Mar 2020"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(shiny)
library(plotly)
library(ggplot2)
## Loading required package: viridisLite



```

_You are welcome to play around with the widgets below to see how changes in Hep B Vaccination occurred!_

```{r data, include=FALSE}

load(file = "merged_nhanes.RData")


nhanes_shiny = 
  nhanes %>% 
  mutate(
      hepbvax = factor(hepbvax, levels = c('No Doses', 'Less Than Three Doses', 'At Least Three Doses'), labels = c("Not Vaccinated", "Partially Vaccinated", "Fully Vaccinated"))
      )

#saving this as an object in order to provide separation between nhanes data and any further data manipulation

```

 {.sidebar}
-----------------------------------------------------------------------

```{r, echo = FALSE}
ins_yesno = nhanes_shiny %>% distinct(insany) %>% pull()
edu = nhanes_shiny %>% distinct(educat) %>% pull()
sex = nhanes_shiny %>% distinct(gender) %>% pull()
race = nhanes_shiny %>% distinct(race) %>% pull()
age10 = nhanes_shiny %>% distinct(age_decile) %>% pull()
hepbvaxchoice = nhanes_shiny %>% distinct(hepbvax) %>%  pull()


#checkboxGroupInput("insany", label = h3("Insurance Status"), 
#choices = ins_yesno)

radioButtons(
  inputId = "sex_bin",
  label = h3("Sex (M/F)"),
  choices = sex
)

selectInput(
  inputId = "race_cat",
  label = h3("Race (as coded in NHANES)"), 
  choices = race
)

selectInput(
  inputId = "edu_cat",
  label = h3("Education Level"), 
  choices = edu
)


```

### Hep B Vaccination Status

```{r, echo = FALSE}

renderPlotly({
  nhanes_shiny %>% 
  filter(
         gender == input[["sex_bin"]],
         race == input[["race_cat"]],
         educat == input[["edu_cat"]]) %>% 
  count(hepbvax) %>% 
  plot_ly(x = ~hepbvax, y = ~n, color = ~hepbvax, type = "bar") %>% 
    layout(title = 'Hep B Vaccination Status', plot_bgcolor = "#e5ecf6", xaxis = list(title = 'Hep B Vax Statuses'), 
         yaxis = list(title = '# of Respondents'), legend = list(title=list(text ='<b> Doses </b>')))
})

  
```


### Comparing Vaccination to Age by Insurance ("Yes" or "No")

```{r, echo = FALSE}
renderPlotly({
  nhanes_shiny %>% 
  filter(
         gender == input[["sex_bin"]],
         race == input[["race_cat"]],
         educat == input[["edu_cat"]]
         ) %>% 
    plot_ly(
      x = ~hepbvax,
      y = ~agecrude, 
      split = ~insany,
      type = 'violin',
      box = list(visible = T
                 ),
      meanline = list(
        visible = T
      )
    ) %>% 
    layout(
      xaxis = list(
        title = "Vaccination Status"
      ),
      yaxis = list(
        title = "Age (years)",
        zeroline = F
      )
    )

})
```


