---
title: "Explore our Data"
subtitle: "(NHANES, 2017 - Mar. 2020)"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(shiny)
library(plotly)
library(ggplot2)
## Loading required package: viridisLite



```


```{r data, include=FALSE}

load(file = "merged_nhanes.RData")


nhanes_shiny = 
  nhanes %>% 
  mutate(
      hepbvax = factor(hepbvax, levels = c('No Doses', 'Less Than Three Doses', 'At Least Three Doses')
      ))

#saving this as an object in order to provide separation between nhanes data and any further data manipulation

```

Settings {.sidebar}
-----------------------------------------------------------------------

```{r, echo = FALSE}
ins_yesno = nhanes_shiny %>% distinct(insany) %>% pull()
edu = nhanes_shiny %>% distinct(educat) %>% pull()
sex = nhanes_shiny %>% distinct(gender) %>% pull()
race = nhanes_shiny %>% distinct(race) %>% pull()
age10 = nhanes_shiny %>% distinct(age_decile) %>% pull()
hepbvaxchoice = nhanes_shiny %>% distinct(hepbvax) %>%  pull()


radioButtons(
  inputId = "insurance_any",
  label = h3("Any Insurance Coverage"),
  choices = ins_yesno
)

selectInput(
  inputId = "hepb_vax_cat",
  label = h3("Hep B Vaccination Status"), 
  choices = hepbvaxchoice
)

radioButtons(
  inputId = "sex_bin",
  label = h3("Sex (M/F)"),
  choices = sex
)

selectInput(
  inputId = "race_cat",
  label = h3("Race (as coded in NHANES)"), 
  choices = race
)

selectInput(
  inputId = "edu_cat",
  label = h3("Education Level"), 
  choices = edu
)

selectInput(
  inputId = "age_cat",
  label = h3("Age (Years)"), 
  choices = age10
)

```

Column {data-width=650}
-----------------------------------------------------------------------

### Hep B Vaccination Status

```{r, echo = FALSE}

renderPlotly({
  nhanes_shiny %>% 
  filter(insany == input[["insurance_any"]],
         gender == input[["sex_bin"]],
         race == input[["race_cat"]],
         educat == input[["edu_cat"]],
         age_decile == input[["age_cat"]],
          hepbvax == input[["hepb_vax_cat"]]
         ) %>% 
  count(hepbvax) %>% 
  plot_ly(x = ~hepbvax, y = ~n, color = ~hepbvax, type = "bar") %>% 
    layout(title = 'Hep B Vaccination Status', plot_bgcolor = "#e5ecf6", xaxis = list(title = '# of Hep B Vax Doses'), 
         yaxis = list(title = '# of Respondents'), legend = list(title=list(text ='<b> Doses </b>')))
})

  
```

Column {data-width=350}
-----------------------------------------------------------------------

### History of Hep B

```{r, echo = FALSE}

renderPlot({
  nhanes_shiny %>% 
  filter(insany == input[["insurance_any"]],
         gender == input[["sex_bin"]],
         race == input[["race_cat"]],
         educat == input[["edu_cat"]],
         age_decile == input[["age_cat"]],
         hepbvax == input[["hepb_vax_cat"]]
         ) %>% 
  ggplot(aes(x = agecrude, color = hepb)) + geom_density() + 
  geom_vline(aes(xintercept = mean(agecrude), color = hepb),linetype = "dashed") + 
    labs(
    x = "Age (years)",
    y = "Density"
    ) 
})
```

### History of Hep C

```{r, echo = FALSE}
renderPlot({
  nhanes_shiny %>% 
  filter(insany == input[["insurance_any"]],
         gender == input[["sex_bin"]],
         race == input[["race_cat"]],
         educat == input[["edu_cat"]],
         age_decile == input[["age_cat"]],
         hepbvax == input[["hepb_vax_cat"]]
         ) %>% 
  ggplot(aes(x = agecrude, color = hepc)) + geom_density() + 
  geom_vline(aes(xintercept = mean(agecrude), color = hepc),linetype = "dashed") + 
  labs(
    x = "Age (years)",
    y = "Density"
    ) 
})
```

