---
title: "Yuchen Hua"
output:
  html_document:
    toc: true
    toc_float: true
    theme: cerulean
---

## Yuchen Hua ##

### Education ###
__Graudate School__: CUMC                              New York, NY    09/2022-Present
Degree: M.S. in Biostatistics 
__Undergraduate__: Brandeis University   Waltham, MA   08/2018-12/2021
Degree: B.S. in Biochemistry

### Research Projects ###
__Computational Study of COVID-19 Antibodies and Structural Implications on Future Antibody Development__

__► Shanghai Jiao Tong University, School of Pharmacy (Advisor : Prof. Buyong Ma) 07 – 08/2021__



__Review of Different Glucose-responsive Insulin Treatments for Type I Diabetes, the Corresponding Biomaterials, and Drug Delivery Methods__

__► Cornell University, Collaborative Online Research (Advisor: Prof. Minglin Ma) 08 – 09/2020__

### Internship ###
__Summer Research Intern (Supervisor : Dr. Yafeng Zhou, Vasculocardiology Department) 06 – 07/2019__

Been a research assistant to organize and clean the clinical data of over 100 oatients with acute myocardial infarction (AMI) to verify the efficacy of a new drug treatment. 
